import type { CompassSector, MaterialityTopicDef } from "@/lib/compass/types";

const T = (
  def: Omit<MaterialityTopicDef, "sectorPrior"> & { impact: number; financial: number },
): MaterialityTopicDef => ({
  ...def,
  sectorPrior: { impact: def.impact, financial: def.financial },
});

const GENERAL: MaterialityTopicDef[] = [
  T({
    id: "ghg_emissions",
    griRef: "GRI 305",
    esrsRef: "ESRS E1",
    pillar: "E",
    label_en: "GHG emissions & climate",
    label_th: "การปล่อย GHG และสภาพภูมิอากาศ",
    summary_en: "Scope 1–3 emissions and climate transition risks.",
    summary_th: "การปล่อย Scope 1–3 และความเสี่ยงการเปลี่ยนแปลงสภาพภูมิอากาศ",
    impact: 4,
    financial: 4,
    actionHints: ["ev_commute", "energy"],
    interestTags: ["climate", "carbon"],
  }),
  T({
    id: "energy",
    griRef: "GRI 302",
    esrsRef: "ESRS E1",
    pillar: "E",
    label_en: "Energy use & efficiency",
    label_th: "การใช้พลังงานและประสิทธิภาพ",
    summary_en: "Energy consumption, renewables, and efficiency.",
    summary_th: "การใช้พลังงาน พลังงานหมุนเวียน และประสิทธิภาพ",
    impact: 3,
    financial: 3,
    actionHints: ["energy"],
    interestTags: ["energy", "carbon"],
  }),
  T({
    id: "waste",
    griRef: "GRI 306",
    esrsRef: "ESRS E5",
    pillar: "E",
    label_en: "Waste & circularity",
    label_th: "ของเสียและเศรษฐกิจหมุนเวียน",
    summary_en: "Waste generation, recycling, and circular design.",
    summary_th: "การเกิดของเสีย การรีไซเคิล และการออกแบบหมุนเวียน",
    impact: 3,
    financial: 2,
    actionHints: ["recycle"],
    interestTags: ["carbon"],
  }),
  T({
    id: "occupational_health",
    griRef: "GRI 403",
    esrsRef: "ESRS S1",
    pillar: "S",
    label_en: "Occupational health & safety",
    label_th: "อาชีวอนามัยและความปลอดภัย",
    summary_en: "Worker health, safety systems, and incident prevention.",
    summary_th: "สุขภาพและความปลอดภัยของผู้ปฏิบัติงาน",
    impact: 4,
    financial: 3,
    actionHints: ["tree_plant"],
    interestTags: ["social"],
  }),
  T({
    id: "diversity",
    griRef: "GRI 405",
    esrsRef: "ESRS S1",
    pillar: "S",
    label_en: "Diversity & equal opportunity",
    label_th: "ความหลากหลายและโอกาสเท่าเทียม",
    summary_en: "Inclusive workforce and equal opportunity practices.",
    summary_th: " workforce ที่หลากหลายและโอกาสที่เท่าเทียม",
    impact: 3,
    financial: 2,
    actionHints: ["tree_plant"],
    interestTags: ["social"],
  }),
  T({
    id: "local_communities",
    griRef: "GRI 413",
    esrsRef: "ESRS S3",
    pillar: "S",
    label_en: "Local communities",
    label_th: "ชุมชนท้องถิ่น",
    summary_en: "Community engagement and local impact management.",
    summary_th: "การมีส่วนร่วมและจัดการผลกระทบต่อชุมชน",
    impact: 3,
    financial: 2,
    actionHints: ["tree_plant"],
    interestTags: ["social"],
  }),
  T({
    id: "governance",
    griRef: "GRI 2",
    esrsRef: "ESRS G1",
    pillar: "G",
    label_en: "Governance & ethics",
    label_th: "ธรรมาภิบาลและจริยธรรม",
    summary_en: "Board oversight, ethics, and ESG governance.",
    summary_th: "การกำกับดูแล จริยธรรม และธรรมาภิบาล ESG",
    impact: 3,
    financial: 4,
    actionHints: ["energy"],
    interestTags: ["governance", "reporting"],
  }),
  T({
    id: "anti_corruption",
    griRef: "GRI 205",
    esrsRef: "ESRS G1",
    pillar: "G",
    label_en: "Anti-corruption",
    label_th: "ต่อต้านการทุจริต",
    summary_en: "Bribery prevention and compliance programs.",
    summary_th: "การป้องกันสินบนและโปรแกรม compliance",
    impact: 3,
    financial: 4,
    actionHints: ["energy"],
    interestTags: ["governance"],
  }),
];

const MANUFACTURING: MaterialityTopicDef[] = [
  ...GENERAL.map((t) => {
    if (t.id === "ghg_emissions") return { ...t, sectorPrior: { impact: 5, financial: 5 } };
    if (t.id === "energy") return { ...t, sectorPrior: { impact: 5, financial: 4 } };
    return t;
  }),
  T({
    id: "water",
    griRef: "GRI 303",
    esrsRef: "ESRS E3",
    pillar: "E",
    label_en: "Water & effluents",
    label_th: "น้ำและน้ำเสีย",
    summary_en: "Water withdrawal, discharge, and stress-region risks.",
    summary_th: "การใช้น้ำ การปล่อยน้ำเสีย และความเสี่ยงในพื้นที่ขาดแคลนน้ำ",
    impact: 5,
    financial: 4,
    actionHints: ["recycle", "energy"],
    interestTags: ["climate"],
  }),
  T({
    id: "supplier_env",
    griRef: "GRI 308",
    esrsRef: "ESRS E1",
    pillar: "E",
    label_en: "Supplier environmental assessment",
    label_th: "ประเมินสิ่งแวดล้อมซัพพลายเออร์",
    summary_en: "Supply chain environmental due diligence.",
    summary_th: "การ due diligence สิ่งแวดล้อมในห่วงโซ่อุปทาน",
    impact: 4,
    financial: 4,
    actionHints: ["recycle"],
    interestTags: ["supply_chain"],
  }),
].filter((t, i, arr) => arr.findIndex((x) => x.id === t.id) === i);

const SERVICES: MaterialityTopicDef[] = GENERAL.map((t) => {
  if (t.id === "ghg_emissions") return { ...t, sectorPrior: { impact: 3, financial: 3 } };
  if (t.id === "energy") return { ...t, sectorPrior: { impact: 3, financial: 3 } };
  if (t.id === "waste") return { ...t, sectorPrior: { impact: 2, financial: 2 } };
  return t;
}).concat([
  T({
    id: "customer_privacy",
    griRef: "GRI 418",
    esrsRef: "ESRS S4",
    pillar: "S",
    label_en: "Customer privacy",
    label_th: "ความเป็นส่วนตัวของลูกค้า",
    summary_en: "Data protection and customer privacy practices.",
    summary_th: "การคุ้มครองข้อมูลและความเป็นส่วนตัวของลูกค้า",
    impact: 4,
    financial: 4,
    actionHints: ["energy"],
    interestTags: ["governance"],
  }),
]);

const CONSTRUCTION: MaterialityTopicDef[] = [
  T({
    id: "ghg_emissions",
    griRef: "GRI 305",
    esrsRef: "ESRS E1",
    pillar: "E",
    label_en: "Embodied carbon & GHG",
    label_th: "Carbon ฝังตัวและ GHG",
    summary_en: "Embodied carbon in materials and construction-phase emissions.",
    summary_th: "Carbon ฝังตัวในวัสดุและการปล่อยระหว่างก่อสร้าง",
    impact: 5,
    financial: 5,
    actionHints: ["ev_commute", "energy"],
    interestTags: ["carbon", "climate"],
  }),
  T({
    id: "energy",
    griRef: "GRI 302",
    esrsRef: "ESRS E1",
    pillar: "E",
    label_en: "Site energy & fuel",
    label_th: "พลังงานและเชื้อเพลิงหน้างาน",
    summary_en: "Fuel use, equipment efficiency, and renewable power on site.",
    summary_th: "การใช้เชื้อเพลิง ประสิทธิภาพเครื่องจักร และพลังงานหมุนเวียนหน้างาน",
    impact: 4,
    financial: 4,
    actionHints: ["energy"],
    interestTags: ["energy"],
  }),
  T({
    id: "waste",
    griRef: "GRI 306",
    esrsRef: "ESRS E5",
    pillar: "E",
    label_en: "Construction waste & materials",
    label_th: "ของเสียก่อสร้างและวัสดุ",
    summary_en: "C&D waste, reuse, and circular material specs.",
    summary_th: "ของเสียจากการก่อสร้าง การนำกลับมาใช้ และ spec วัสดุหมุนเวียน",
    impact: 5,
    financial: 4,
    actionHints: ["recycle"],
    interestTags: ["carbon"],
  }),
  T({
    id: "water",
    griRef: "GRI 303",
    esrsRef: "ESRS E3",
    pillar: "E",
    label_en: "Water on site",
    label_th: "การใช้น้ำหน้างาน",
    summary_en: "Dust suppression, concrete curing, and discharge control.",
    summary_th: "การลดฝุ่น การบ่มคอนกรีต และการควบคุมน้ำทิ้ง",
    impact: 4,
    financial: 3,
    actionHints: ["recycle"],
    interestTags: ["climate"],
  }),
  T({
    id: "occupational_health",
    griRef: "GRI 403",
    esrsRef: "ESRS S1",
    pillar: "S",
    label_en: "Site safety & worker health",
    label_th: "ความปลอดภัยหน้างาน",
    summary_en: "High-risk work, PPE, and incident prevention on sites.",
    summary_th: "งานเสี่ยงสูง PPE และการป้องกันอุบัติเหตุหน้างาน",
    impact: 5,
    financial: 5,
    actionHints: ["tree_plant"],
    interestTags: ["social"],
  }),
  T({
    id: "local_communities",
    griRef: "GRI 413",
    esrsRef: "ESRS S3",
    pillar: "S",
    label_en: "Community & nuisance",
    label_th: "ชุมชนและผลกระทบรบกวน",
    summary_en: "Noise, traffic, and community relations near projects.",
    summary_th: "เสียง การจราจร และความสัมพันธ์กับชุมชนใกล้โครงการ",
    impact: 5,
    financial: 4,
    actionHints: ["tree_plant"],
    interestTags: ["social"],
  }),
  T({
    id: "supplier_env",
    griRef: "GRI 308",
    esrsRef: "ESRS E1",
    pillar: "E",
    label_en: "Responsible sourcing",
    label_th: "จัดหาวัสดุอย่างรับผิดชอบ",
    summary_en: "Sustainable materials and subcontractor environmental standards.",
    summary_th: "วัสดุยั่งยืนและมาตรฐานสิ่งแวดล้อมของผู้รับเหมาช่วง",
    impact: 4,
    financial: 4,
    actionHints: ["recycle"],
    interestTags: ["supply_chain"],
  }),
  T({
    id: "biodiversity",
    griRef: "GRI 304",
    esrsRef: "ESRS E4",
    pillar: "E",
    label_en: "Biodiversity & land use",
    label_th: "ความหลากหลายทางชีวภาพและที่ดิน",
    summary_en: "Site ecology, land disturbance, and habitat protection.",
    summary_th: "นิเวศหน้างาน การรบกวนที่ดิน และการคุ้มครองถิ่นที่อยู่อาศัย",
    impact: 4,
    financial: 3,
    actionHints: ["tree_plant"],
    interestTags: ["biodiversity"],
  }),
];

const ENERGY: MaterialityTopicDef[] = [
  T({
    id: "ghg_emissions",
    griRef: "GRI 305",
    esrsRef: "ESRS E1",
    pillar: "E",
    label_en: "Scope 1–3 GHG & transition",
    label_th: "GHG Scope 1–3 และการเปลี่ยนผ่าน",
    summary_en: "Operational and value-chain emissions; transition planning.",
    summary_th: "การปล่อยจากการดำเนินงานและห่วงโซ่คุณค่า แผนการเปลี่ยนผ่าน",
    impact: 5,
    financial: 5,
    actionHints: ["ev_commute", "energy"],
    interestTags: ["carbon", "climate"],
  }),
  T({
    id: "energy",
    griRef: "GRI 302",
    esrsRef: "ESRS E1",
    pillar: "E",
    label_en: "Energy mix & efficiency",
    label_th: "พลังงานผสมและประสิทธิภาพ",
    summary_en: "Generation mix, grid losses, and efficiency programs.",
    summary_th: "พลังงานผสม การสูญเสียในระบบ และโปรแกรมประสิทธิภาพ",
    impact: 5,
    financial: 5,
    actionHints: ["energy"],
    interestTags: ["energy"],
  }),
  T({
    id: "water",
    griRef: "GRI 303",
    esrsRef: "ESRS E3",
    pillar: "E",
    label_en: "Water use (thermal/cooling)",
    label_th: "การใช้น้ำ (ระบบทำความเย็น)",
    summary_en: "Cooling water, thermal plants, and discharge quality.",
    summary_th: "น้ำหล่อเย็น โรงไฟฟ้าความร้อน และคุณภาพน้ำทิ้ง",
    impact: 4,
    financial: 4,
    actionHints: ["recycle"],
    interestTags: ["climate"],
  }),
  T({
    id: "biodiversity",
    griRef: "GRI 304",
    esrsRef: "ESRS E4",
    pillar: "E",
    label_en: "Biodiversity impacts",
    label_th: "ผลกระทบต่อความหลากหลายทางชีวภาพ",
    summary_en: "Land use, habitats, and restoration near assets.",
    summary_th: "การใช้ที่ดิน ถิ่นที่อยู่อาศัย และการฟื้นฟูใกล้สินทรัพย์",
    impact: 4,
    financial: 3,
    actionHints: ["tree_plant"],
    interestTags: ["biodiversity"],
  }),
  T({
    id: "occupational_health",
    griRef: "GRI 403",
    esrsRef: "ESRS S1",
    pillar: "S",
    label_en: "Process safety & workforce",
    label_th: "ความปลอดภัยกระบวนการและแรงงาน",
    summary_en: "Major accident prevention and workforce health.",
    summary_th: "การป้องกันอุบัติร้ายแรงและสุขภาพแรงงาน",
    impact: 5,
    financial: 5,
    actionHints: ["tree_plant"],
    interestTags: ["social"],
  }),
  T({
    id: "local_communities",
    griRef: "GRI 413",
    esrsRef: "ESRS S3",
    pillar: "S",
    label_en: "Affected communities",
    label_th: "ชุมชนที่ได้รับผลกระทบ",
    summary_en: "Just transition and community engagement.",
    summary_th: "การเปลี่ยนผ่านที่เป็นธรรมและการมีส่วนร่วมชุมชน",
    impact: 4,
    financial: 4,
    actionHints: ["tree_plant"],
    interestTags: ["social"],
  }),
  T({
    id: "governance",
    griRef: "GRI 2",
    esrsRef: "ESRS G1",
    pillar: "G",
    label_en: "Climate governance",
    label_th: "ธรรมาภิบาลด้าน climate",
    summary_en: "Board climate oversight and disclosure alignment.",
    summary_th: "การกำกับดูแล climate ของคณะกรรมการและการเปิดเผย",
    impact: 4,
    financial: 5,
    actionHints: ["energy"],
    interestTags: ["governance", "reporting"],
  }),
  T({
    id: "public_policy",
    griRef: "GRI 415",
    esrsRef: "ESRS G1",
    pillar: "G",
    label_en: "Public policy & advocacy",
    label_th: "นโยบายสาธารณะและการสื่อสาร",
    summary_en: "Policy engagement aligned with climate goals.",
    summary_th: "การมีส่วนร่วมนโยบายสอดคล้องเป้าหมาย climate",
    impact: 3,
    financial: 4,
    actionHints: ["energy"],
    interestTags: ["governance"],
  }),
];

export const SECTOR_LABELS: Record<CompassSector, { en: string; th: string }> = {
  general: { en: "General / cross-sector", th: "ทั่วไป / ข้ามอุตสาหกรรม" },
  manufacturing: { en: "Manufacturing", th: "การผลิต" },
  services: { en: "Services", th: "บริการ" },
  construction: { en: "Construction", th: "ก่อสร้าง" },
  energy: { en: "Energy & utilities", th: "พลังงานและสาธารณูปโภค" },
};

const LIBRARY: Record<CompassSector, MaterialityTopicDef[]> = {
  general: GENERAL,
  manufacturing: MANUFACTURING.slice(0, 8),
  services: SERVICES.slice(0, 8),
  construction: CONSTRUCTION,
  energy: ENERGY,
};

export function getTopicsForSector(sector: CompassSector): MaterialityTopicDef[] {
  return LIBRARY[sector] ?? GENERAL;
}

export function defaultRatings(topics: MaterialityTopicDef[]): Record<string, number> {
  return Object.fromEntries(topics.map((t) => [t.id, 3]));
}
