/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedExpertsRouteImport } from './routes/_authenticated/experts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge.index'
import { Route as AuthenticatedExpertsIndexRouteImport } from './routes/_authenticated/experts.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSettingsActivityRouteImport } from './routes/_authenticated/settings.activity'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings.account'
import { Route as AuthenticatedKnowledgeNewRouteImport } from './routes/_authenticated/knowledge.new'
import { Route as AuthenticatedKnowledgeSlugRouteImport } from './routes/_authenticated/knowledge.$slug'
import { Route as AuthenticatedExpertsIdRouteImport } from './routes/_authenticated/experts.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSetupRouteImport } from './routes/_authenticated/admin.setup'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpertsRoute = AuthenticatedExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedExpertsIndexRoute =
  AuthenticatedExpertsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpertsRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSettingsActivityRoute =
  AuthenticatedSettingsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedKnowledgeNewRoute =
  AuthenticatedKnowledgeNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedKnowledgeSlugRoute =
  AuthenticatedKnowledgeSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedExpertsIdRoute = AuthenticatedExpertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedExpertsRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSetupRoute = AuthenticatedAdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/experts': typeof AuthenticatedExpertsRouteWithChildren
  '/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/experts/$id': typeof AuthenticatedExpertsIdRoute
  '/knowledge/$slug': typeof AuthenticatedKnowledgeSlugRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/experts/': typeof AuthenticatedExpertsIndexRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/experts/$id': typeof AuthenticatedExpertsIdRoute
  '/knowledge/$slug': typeof AuthenticatedKnowledgeSlugRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/experts': typeof AuthenticatedExpertsIndexRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/experts': typeof AuthenticatedExpertsRouteWithChildren
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/setup': typeof AuthenticatedAdminSetupRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/experts/$id': typeof AuthenticatedExpertsIdRoute
  '/_authenticated/knowledge/$slug': typeof AuthenticatedKnowledgeSlugRoute
  '/_authenticated/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/experts/': typeof AuthenticatedExpertsIndexRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/community'
    | '/dashboard'
    | '/experts'
    | '/knowledge'
    | '/marketplace'
    | '/settings'
    | '/admin/activity'
    | '/admin/setup'
    | '/admin/users'
    | '/experts/$id'
    | '/knowledge/$slug'
    | '/knowledge/new'
    | '/settings/account'
    | '/settings/activity'
    | '/admin/'
    | '/experts/'
    | '/knowledge/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/marketplace'
    | '/admin/activity'
    | '/admin/setup'
    | '/admin/users'
    | '/experts/$id'
    | '/knowledge/$slug'
    | '/knowledge/new'
    | '/settings/account'
    | '/settings/activity'
    | '/admin'
    | '/experts'
    | '/knowledge'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/experts'
    | '/_authenticated/knowledge'
    | '/_authenticated/marketplace'
    | '/_authenticated/settings'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/setup'
    | '/_authenticated/admin/users'
    | '/_authenticated/experts/$id'
    | '/_authenticated/knowledge/$slug'
    | '/_authenticated/knowledge/new'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/activity'
    | '/_authenticated/admin/'
    | '/_authenticated/experts/'
    | '/_authenticated/knowledge/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experts': {
      id: '/_authenticated/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof AuthenticatedExpertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/experts/': {
      id: '/_authenticated/experts/'
      path: '/'
      fullPath: '/experts/'
      preLoaderRoute: typeof AuthenticatedExpertsIndexRouteImport
      parentRoute: typeof AuthenticatedExpertsRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/settings/activity': {
      id: '/_authenticated/settings/activity'
      path: '/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof AuthenticatedSettingsActivityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/knowledge/new': {
      id: '/_authenticated/knowledge/new'
      path: '/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof AuthenticatedKnowledgeNewRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/knowledge/$slug': {
      id: '/_authenticated/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof AuthenticatedKnowledgeSlugRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/experts/$id': {
      id: '/_authenticated/experts/$id'
      path: '/$id'
      fullPath: '/experts/$id'
      preLoaderRoute: typeof AuthenticatedExpertsIdRouteImport
      parentRoute: typeof AuthenticatedExpertsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setup': {
      id: '/_authenticated/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AuthenticatedAdminSetupRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminSetupRoute: typeof AuthenticatedAdminSetupRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminSetupRoute: AuthenticatedAdminSetupRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedExpertsRouteChildren {
  AuthenticatedExpertsIdRoute: typeof AuthenticatedExpertsIdRoute
  AuthenticatedExpertsIndexRoute: typeof AuthenticatedExpertsIndexRoute
}

const AuthenticatedExpertsRouteChildren: AuthenticatedExpertsRouteChildren = {
  AuthenticatedExpertsIdRoute: AuthenticatedExpertsIdRoute,
  AuthenticatedExpertsIndexRoute: AuthenticatedExpertsIndexRoute,
}

const AuthenticatedExpertsRouteWithChildren =
  AuthenticatedExpertsRoute._addFileChildren(AuthenticatedExpertsRouteChildren)

interface AuthenticatedKnowledgeRouteChildren {
  AuthenticatedKnowledgeSlugRoute: typeof AuthenticatedKnowledgeSlugRoute
  AuthenticatedKnowledgeNewRoute: typeof AuthenticatedKnowledgeNewRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
}

const AuthenticatedKnowledgeRouteChildren: AuthenticatedKnowledgeRouteChildren =
  {
    AuthenticatedKnowledgeSlugRoute: AuthenticatedKnowledgeSlugRoute,
    AuthenticatedKnowledgeNewRoute: AuthenticatedKnowledgeNewRoute,
    AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  }

const AuthenticatedKnowledgeRouteWithChildren =
  AuthenticatedKnowledgeRoute._addFileChildren(
    AuthenticatedKnowledgeRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsActivityRoute: typeof AuthenticatedSettingsActivityRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsActivityRoute: AuthenticatedSettingsActivityRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpertsRoute: typeof AuthenticatedExpertsRouteWithChildren
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRouteWithChildren
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpertsRoute: AuthenticatedExpertsRouteWithChildren,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRouteWithChildren,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
